### PR TITLE
Feature/add touch support

### LINKED ISSUE #60: Support for Touch Events
**Is your feature request related to a problem? Please describe.**
I can't use it on the iPad (can not drag nodes or connections).

**Describe the solution you'd like**
It looks like the library does not support Touch Events

### PR DESCRIPTION
**Pull request by joancc**
## Description
Add touch support for:
1. Dragging nodes
2. Dragging segments from nodes
3. Creating segments on _touchend_ at new port

## Related Issue
Closes #60 

## Motivation and Context
Closes #60 

## How Has This Been Tested?
All existing tests are passing.
Tested on the Chrome mobile simulator on a mac and Safari on an iPad.

### CODE REVIEW

**Comment by joancc** [comment]
@antonioru you mentioned in the original issue the use of useMouse from your hooks library, but I was unable to find a reference to it. Let me know if I missed something.

**Comment by joancc** [comment]
Marked as WIP for now since it's breaking related to issue #68

**Comment by antonioru** [comment]
Hello @joancc 
thank you for the huge merge request, I really appreciate your effort! 
Yes, I think I've mentioned the `useMouse` hook from the library `beautiful-react-hooks` in another issue, but recently I'm working on pan/zoom functionality for the canvas and I've found a fancy way to use both touch and mouse events at the same time, please take a look at this:
https://github.com/beautifulinteractions/beautiful-react-diagrams/pull/70

**Comment by joancc** [comment]
Thanks @antonioru! I think I managed totrack the relevant stuff to useCanvasPanHandlers.js:

```
const getMouseEventPoint = (e) => ({ x: e.pageX, y: e.pageY });
const getTouchEventPoint = (e) => getMouseEventPoint(e.changedTouches[0]);
const getEventPoint = isTouch ? getTouchEventPoint : getMouseEventPoint;
```

I'll recreate the CONSTANTS file in my PR and perhaps ass this mouse/touch logic in a separate hook?

I'll look closer at the use of these in your PR, butI think that's the important stuff, right?

**Comment by antonioru** [comment]
Yes, you're absolutely right: it is very important to support the touch event as indeed I was already working on it: 

https://github.com/beautifulinteractions/beautiful-react-diagrams/blob/feature/canvas-ext/src/components/NodeDraggableElement/useDragAround.js

:) 

Btw, would you mind to target your PR to the `feature/canvas` branch? 
That is the branch of the next version  `0.6.0` which will definitely solve a lot of issues and improve performances

**Comment by joancc** [comment]
Closing in favor of #82

**Pull request closed without merging**
